site_name: Hypixel Skyblock Mods
site_url: https://nealkitt.moe
repo_name: Nealkitt/Hypixel-Mods-Wiki
repo_url: https://github.com/nealkitt/Hypixel-Mods-Wiki
nav:
  - index.md
  - SkyHanni Features:
    - SkyHanni/GUI.md
    - SkyHanni/Garden.md
    - SkyHanni/Crimson_Isle.md

  
theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.top
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.indexes
    - content.action.edit
    - search.suggest
    - search.share
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: lime
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode