site_name: Stella's Webpage
site_url: https://nealkitt.moe
repo_name: Nealkitt/Stellas-Website
repo_url: https://github.com/nealkitt/Stellas-Website
nav:
  - index.md
  - Mods Features:
    - mods_features/index.md
    - SkyHanni Features:
      - mods_features/SkyHanni/index.md
      - mods_features/SkyHanni/GUI.md
      - mods_features/SkyHanni/Garden.md
      - mods_features/SkyHanni/Crimson_Isle.md
      - mods_features/SkyHanni/The_Rift.md
      - mods_features/SkyHanni/Fishing.md
      - mods_features/SkyHanni/Mining.md
      - mods_features/SkyHanni/Combat.md
      - mods_features/SkyHanni/Slayer.md



  
theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.top
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.indexes
    - content.action.edit
    - search.suggest
    - search.share
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: lime
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode